services:
  db:
    image: mysql:9
    environment:
      MYSQL_DATABASE: appabovedb
      MYSQL_ROOT_PASSWORD: La@123465
    ports:
      - "3407:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: appabove-be-app:latest
    ports:
      - "9119:8080"
    depends_on:
      - db
    env_file:
      - .env

#For local
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#    env_file:
#      - .env